src/main/java/com/wiseach/teamlog/model/User.java
package com.wiseach.teamlog.model;

import com.wiseach.teamlog.Constants;
import com.wiseach.teamlog.db.UserAuthDBHelper;
import com.wiseach.teamlog.utils.FileUtils;
import com.wiseach.teamlog.web.security.UserAuthProcessor;

/**
 * User: Arlen Tan
 * 12-8-9 下午6:29
 */
public class User {
    private Long id;
    private String email,username,password,avatar;
    private Boolean disabled;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAvatar() {
        return FileUtils.getUserAvatarURL(avatar);
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Boolean getDisabled() {
        return disabled;
    }

    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    public boolean getAdmin() {
        return username.equals(UserAuthDBHelper.ADMIN_USER);
    }

}

src/main/java/com/wiseach/teamlog/model/WorkLog.java
package com.wiseach.teamlog.model;

import java.util.Date;

/**
 * User: Arlen Tan
 * 12-8-30 上午9:57
 */
public class WorkLog {
    private Long id;
    private String description,tags;
    private Date startTime,endTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}

src/main/java/com/wiseach/teamlog/web/actions/ChangeAvatarActionBean.java
package com.wiseach.teamlog.web.actions;

import com.wiseach.teamlog.Constants;
import com.wiseach.teamlog.db.UserAuthDBHelper;
import com.wiseach.teamlog.utils.FileUtils;
import com.wiseach.teamlog.web.resolutions.JsonResolution;
import com.wiseach.teamlog.web.security.UserAuthProcessor;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.util.StringUtil;
import net.sourceforge.stripes.validation.Validate;

/**
 * User: Arlen Tan
 * 12-8-9 下午6:19
 */
@UrlBinding("/change-avatar")
public class ChangeAvatarActionBean extends BaseActionBean {

    @DontValidate
    @DefaultHandler
    public Resolution view() {
        return new ForwardResolution(ViewHelper.CHANGE_AVATAR_PAGE);
    }

    @DontValidate
    public Resolution uploadAvatar() {
        String filename;
        if (avatar!=null) {
            Long userId = UserAuthProcessor.getUserId(getContext());
                    filename = userId +".jpg";
                    UserAuthDBHelper.updateUserAvatar(userId, filename);
                    FileUtils.saveBigAvatar(avatar,getRealPath(),filename);
        } else {
            filename=Constants.EMPTY_STRING;
        }

        return new JsonResolution<String>(filename);
    }

    public Resolution resizeAvatar() {
        String[] dim = StringUtil.standardSplit(dimension);

        try {
            Integer x=Double.valueOf(dim[0]).intValue(),y=Double.valueOf(dim[1]).intValue(),width = Double.valueOf(dim[2]).intValue();
            FileUtils.saveAvatar(getRealPath(),x,y,width,UserAuthDBHelper.getUserAvatar(UserAuthProcessor.getUserId(getContext())));
        } catch (Exception e) {
            addLocalizableError("dimension", "dimension.params.error");
            return view();
        }

        UserAuthProcessor.updateUserAvatar(getContext());

        return ViewHelper.getHomePageResolution();
    }

    @Validate(required = true)
    private String dimension;
    private String userAvatar;
    private FileBean avatar;

    public String getDimension() {
        return dimension;
    }

    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    public String getBigAvatar() {
        if (userAvatar == null) {
            userAvatar = FileUtils.getUserBigAvatarURL(UserAuthProcessor.getUserId(getContext()));
        }
        return userAvatar;
    }

    public FileBean getAvatar() {
        return avatar;
    }

    public void setAvatar(FileBean avatar) {
        this.avatar = avatar;
    }
}

src/main/java/com/wiseach/teamlog/web/actions/InviteUserActionBean.java
package com.wiseach.teamlog.web.actions;

import com.wiseach.teamlog.db.UserAuthDBHelper;
import com.wiseach.teamlog.model.User;
import com.wiseach.teamlog.utils.EmailSender;
import com.wiseach.teamlog.web.WebUtils;
import com.wiseach.teamlog.web.security.UserAuthProcessor;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.util.StringUtil;
import net.sourceforge.stripes.validation.Validate;

import java.util.ArrayList;
import java.util.List;

/**
 * User: Arlen Tan
 * 12-8-10 上午8:56
 */
@UrlBinding("/invite-users")
public class InviteUserActionBean extends BaseActionBean {

    private static final String INVITE_USER_ERROR_DESCRIPTION = "invite.user.error.description";

    @DontValidate
    @DefaultHandler
    public Resolution view() {
        if (UserAuthProcessor.isAdmin(getContext())) {
            return new ForwardResolution(ViewHelper.INVITE_USER_PAGE);
        }

        return returnNoAdminResolution(INVITE_USER_ERROR_DESCRIPTION);
    }


    public Resolution invite(){
        if (UserAuthProcessor.isAdmin(getContext())) {
            String[] emails = StringUtil.standardSplit(inviteEmail);
            ArrayList<String> registeredEmails = new ArrayList<String>();

            String email,uuid,activateUrl;
            for (int i = 0; i < emails.length; i++) {
                email = emails[i];
                if (UserAuthDBHelper.emailHasRegistered(email)) {
                    registeredEmails.add(email);
                    continue;
                }
                uuid = UserAuthDBHelper.createUser(null,email);
                activateUrl = WebUtils.ACTIVATE_URL+uuid;
                EmailSender.send(email,email,getMessage("email.activate.invite.user.subject"),getMessage("email.activate.invite.user",email,activateUrl,activateUrl));
            }

            if (registeredEmails.size()>0) {
                addError("inviteEmail", getMessage("error.message.email.duplicate", StringUtil.combineParts(registeredEmails)));
            }

            return view();
        }

        return returnNoAdminResolution(INVITE_USER_ERROR_DESCRIPTION);
    }

    @Validate(required = true)
    private String inviteEmail;

    public String getInviteEmail() {
        return inviteEmail;
    }

    public void setInviteEmail(String inviteEmail) {
        this.inviteEmail = inviteEmail;
    }

    public List<User> getUserList() {
        if (UserAuthProcessor.isAdmin(getContext())) {
            return UserAuthDBHelper.getUserList();
        } else {
            return null;
        }
    }
}

src/main/java/com/wiseach/teamlog/web/actions/SettingActionBean.java
package com.wiseach.teamlog.web.actions;

import com.wiseach.teamlog.db.CommonDBHelper;
import com.wiseach.teamlog.web.resolutions.JsonResolution;
import com.wiseach.teamlog.web.security.UserAuthProcessor;
import net.sourceforge.stripes.action.*;
import net.sourceforge.stripes.util.StringUtil;
import net.sourceforge.stripes.validation.Validate;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Created with IntelliJ IDEA.
 * User: sean
 * Date: 12-10-30
 * Time: 下午11:13
 * To change this template use File | Settings | File Templates.
 */
@UrlBinding("/setting")
public class SettingActionBean extends BaseActionBean{

    @DontValidate
    @DefaultHandler
    public Resolution view() {
        if (UserAuthProcessor.isAdmin(getContext())) {
            return new ForwardResolution(ViewHelper.SETTING_PAGE);
        }

        return returnNoAdminResolution("setting.log.type.error.description");
    }

    public Resolution create() {
        if (UserAuthProcessor.isAdmin(getContext())) {
            String types[] = StringUtil.standardSplit(workType);
            String type;
            ArrayList<String> existType = new ArrayList<String>();

            for (int i = 0; i < types.length; i++) {
                type = types[i];
                if (CommonDBHelper.hasTag(type)) {
                    existType.add(type);
                } else {
                    CommonDBHelper.newTag(type);
                }
            }

            if (existType.size()>0) {
                addError("workType", getMessage("error.message.work.type.duplicate", StringUtil.combineParts(existType)));
            }

            return view();
        } else {
            return returnNoAdminResolution("setting.log.type.error.description");
        }
    }

    @DontValidate
    public Resolution deleteWorkType() {
        boolean validateId = typeId != null && typeId > 0;
        if (validateId) {
            validateId = CommonDBHelper.delTag(typeId);
        }

        return new JsonResolution<Boolean>(validateId);
    }

    public Long typeId;
    @Validate(required = true)
    private String workType;

    public String getWorkType() {
        return workType;
    }

    public void setWorkType(String workType) {
        this.workType = workType;
    }

    public List<Map<String, Object>> getAllWorkType() {
        if (UserAuthProcessor.isAdmin(getContext())) {
            return CommonDBHelper.getTags();
        } else {
            return null;
        }
    }
}

src/main/webapp/WEB-INF/views/pages/activate-user.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>

<fmt:message key="activate.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/common-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="activate.description"/></h3>
        <div class="activate-box">
            <s:form beanclass="com.wiseach.teamlog.web.actions.ActivateUserActionBean">
                <s:hidden name="uuid" value="${actionBean.uuid}"/>
                <s:errors field="uuid"/>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <fmt:message key="activate.password" var="yourPassword"/>
                            <span class="add-on"><i class="icon-lock"></i></span><input id="activatePw" class="input-width-std" name="activateNewPassword" value="${actionBean.activateNewPassword}" type="password" placeholder="${yourPassword}" title="${yourPassword}">
                        </div>
                    </div>
                    <s:errors field="activateNewPassword"/>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <fmt:message key="activate.password.retype" var="retypePassword"/>
                            <span class="add-on"><i class="icon-repeat"></i></span><input class="input-width-std" name="activateRetypePassword" value="${actionBean.activateRetypePassword}" type="password" placeholder="${retypePassword}" title="${retypePassword}">
                        </div>
                    </div>
                    <s:errors field="activateRetypePassword"/>
                </div>
                <div class="control-group">
                    <s:submit name="activate" class="btn btn-primary"><fmt:message key="activate.button"/></s:submit>
                </div>
            </s:form>

            <%@include file="/WEB-INF/views/include/password-indicator.jsp"%>
        </div>
        <script type="text/javascript">$('#activatePw').focus();$('#activatePw').keyup(function(){checkStrength($(this).val())});</script>
    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/change-avatar.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="change.avatar.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/login-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <link rel="stylesheet" href="${rootUri}/res/jcrop/jquery.Jcrop.css" media="all" type="text/css">
        <%--<link rel="stylesheet" href="/res/upload/css/jquery.fileupload-ui.css" media="all" type="text/css">--%>
        <script type="text/javascript" src="${rootUri}/res/jcrop/jquery.Jcrop.js"></script>
        <script src="${rootUri}/res/upload/vendor/jquery.ui.widget.js"></script>
        <script src="${rootUri}/res/upload/jquery.iframe-transport.js"></script>
        <script src="${rootUri}/res/upload/jquery.fileupload.js"></script>
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="change.avatar.description"/></h3>
        <div class="row-fluid sub-content" style="margin-top: 20px;">
            <div class="span7">
                <div class="avatar-result"><img id="jcrop-view" src="${actionBean.bigAvatar}" alt="default avatar"></div>
                <s:errors field="demistion"/>
            </div>
            <div class="span5" style="position: relative;">
                <span id="upload" class="btn upload-btn"><fmt:message key="change.avatar.upload"/><input id="avatarInput" name="avatar" type="file"></span>
                <div style="position: absolute;top:182px;">
                    <p><fmt:message key="change.avatar.preview"/></p>
                    <div class="avatar-preview">
                        <img id="preview" src="${actionBean.bigAvatar}" alt="preview avatar">
                    </div>
                </div>
            </div>
        </div>

        <div class="sub-content control-group" style="margin-top: 20px;">
            <s:form beanclass="com.wiseach.teamlog.web.actions.ChangeAvatarActionBean">
                <s:hidden name="dimension" id="dimension"/>
                <s:submit name="resizeAvatar" class="btn btn-primary"><fmt:message key="button.finish.label"/></s:submit>
            </s:form>
        </div>
        <script type="text/javascript">
            $(function(){


                function initJcrop() {
                    var jcropView = $('#jcrop-view');

                    jcropView.Jcrop({
                        onChange: showPreview,
                        onSelect: showPreview,
                        onRelease: hidePreview,
                        setSelect:[0,0,160,160],
                        aspectRatio: 1
                    });

                    // Our simple event handler, called from onChange and onSelect
                    // event handlers, as per the Jcrop invocation above
                    function showPreview(coords)
                    {
                        if (parseInt(coords.w) > 0)
                        {
                            var rx = 100 / coords.w;
                            var ry = 100 / coords.h;

                            $('#preview').css({
                                width: Math.round(rx * $('#jcrop-view').width()) + 'px',
                                height: Math.round(ry * $('#jcrop-view').height()) + 'px',
                                marginLeft: '-' + Math.round(rx * coords.x) + 'px',
                                marginTop: '-' + Math.round(ry * coords.y) + 'px'
                            }).show();
                        }
                        $("#dimension").attr('value',coords.x+','+coords.y+','+coords.w);
                    }

                    function hidePreview()
                    {
                        $('#preview').stop().fadeOut('fast');
                    }
                }

                initJcrop();

                $('#upload').fileupload({
                    url:'${rootUri}/change-avatar/uploadAvatar',
                    fileInput:$('#avatarInput'),
                    done:function(e,d){
                        if (d!='') {
                            var src = "${rootUri}/avatar/avatarTemp/"+ d.result+"?t="+new Date().getMilliseconds();
                            $('.avatar-result').empty().append($('<img id="jcrop-view">').attr('src',src));
                            initJcrop();
                            $('#preview').attr("src",src).show();
                        }
                    }
                })
            });
        </script>
    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/change-password.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="change.password.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/login-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="change.password.description"/></h3>
        <div class="change-password-box">
            <s:form beanclass="com.wiseach.teamlog.web.actions.ChangePasswordActionBean">
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <fmt:message key="change.password.password.current" var="currentPassword"/>
                            <span class="add-on"><i class="icon-lock"></i></span><input id="currentPassword" class="input-width-std" name="currentPassword" type="password" placeholder="${currentPassword}" title="${currentPassword}">
                        </div>
                    </div>
                    <s:errors field="currentPassword"/>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <fmt:message key="change.password.password.new" var="newPassword"/>
                            <span class="add-on"><i class="icon-lock"></i></span><input id="newPassword" class="input-width-std" name="newPassword" type="password" placeholder="${newPassword}" title="${newPassword}">
                        </div>
                    </div>
                    <s:errors field="newPassword"/>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="input-prepend">
                            <fmt:message key="change.password.password.retype" var="retypePassword"/>
                            <span class="add-on"><i class="icon-repeat"></i></span><input class="input-width-std" name="retypePassword" type="password" placeholder="${retypePassword}" title="${retypePassword}">
                        </div>
                    </div>
                    <s:errors field="retypePassword"/>
                </div>
                <div class="control-group">
                    <s:submit name="change" class="btn btn-primary"><fmt:message key="button.finish.label"/></s:submit>
                </div>
            </s:form>

            <%@include file="/WEB-INF/views/include/password-indicator.jsp"%>
        </div>
        <script type="text/javascript">$('#currentPassword').focus();$('#newPassword').keyup(function(){checkStrength($(this).val())});</script>
    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/create-first-user-ok.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="create.first.user.ok.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/common-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="create.first.user.ok.description"/></h3>

        <div class="sub-content">
            <p style="margin: 20px 0;">
                <fmt:message key="create.first.user.ok.info">
                    <fmt:param value="${actionBean.firstUserEmail}"/>
                </fmt:message>
            </p>
            <a class="btn btn-primary" href="${rootUri}/login"><fmt:message key="create.first.user.ok.login"/></a>
        </div>
    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/create-first-user.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="create.first.user.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/common-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="create.first.user.description"/></h3>

        <div class="form-box">
            <s:form beanclass="com.wiseach.teamlog.web.actions.CreateFirstUserActionBean" class="form-inline">
                <div class="input-prepend">
                    <fmt:message key="create.first.user.info" var="firstUserEmail"/>
                    <span class="add-on"><i class="icon-envelope"></i></span><input id="firstUser" style="width: 350px;" name="firstUserEmail" value="${actionBean.firstUserEmail}" type="text" placeholder="${firstUserEmail}" title="${firstUserEmail}">
                </div>
                <s:submit name="create" class="btn btn-primary"><fmt:message key="button.ok.label"/></s:submit>
            </s:form>
            <s:errors field="firstUserEmail"/>
        </div>
        <%@include file="/WEB-INF/views/include/email-failed-reasons.jsp"%>
    </s:layout-component>
</s:layout-render>
<script type="text/javascript">$('#firstUser').focus()</script>

src/main/webapp/WEB-INF/views/pages/invite-users.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="invite.user.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/login-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="invite.user.description"/></h3>
        <div class="form-box">
            <s:form beanclass="com.wiseach.teamlog.web.actions.InviteUserActionBean" class="form-inline">
                <div class="input-prepend">
                    <fmt:message key="invite.user.info" var="inputWorkType"/>
                    <span class="add-on"><i class="icon-envelope"></i></span><input id="inviteEmail" style="width: 740px;" name="inviteEmail" value="${actionBean.inviteEmail}" type="text" placeholder="${inputWorkType}" title="${inputWorkType}">
                </div>
                <s:submit name="invite" class="btn btn-primary"><fmt:message key="button.ok.label"/></s:submit>
            </s:form>
            <s:errors field="inviteEmail"/>
        </div>

        <fmt:message key="invite.user.allow.inviteNewUser" var="iniviteNewUser"/>
        <fmt:message key="invite.user.disable" var="disableUser"/>
        <div class="form-box" style="padding-top: 0px;">
            <div class="user-list">
                <c:forEach items="${actionBean.userList}" var="user">
                    <div class="user-info">
                        <img src="${user.avatar==null?'/res/imgs/default-avatar.png':user.avatar}" alt="${user.username}" class="huge-avatar">
                        <p><a href="mailto:${user.email}">${user.username}</a></p>
                        <%--<label class="checkbox">--%>
                            <%--<input type="checkbox" id="allowInvitation" name="allowInvitation" value="yes" checked="checked">--%>
                            <%--${iniviteNewUser}--%>
                        <%--</label>--%>
                        <label class="checkbox">
                            <input type="checkbox" id="${user.id}" name="disabledUser" value="true" ${user.disabled==null or user.disabled == false?'':'checked'} ${user.admin?'disabled':''}>
                            ${disableUser}
                        </label>
                    </div>
                </c:forEach>
            </div>
            <p class="help-block">
                <fmt:message key="invite.user.help">
                    <fmt:param value="${iniviteNewUser}"/>
                    <fmt:param value="${disableUser}"/>
                </fmt:message>
            </p>
            <a href="${rootUri}/invite-users/finish" class="btn btn-primary" style="margin-top: 20px;"><fmt:message key="invite.user.button.finish"/></a>
        </div>

        <script type="text/javascript">
            $(function () {
                        $('#inviteEmail').focus();
                        $(".user-list :checkbox").on('click', function (e) {
                            var isChecked = ($(e.target).attr('checked') == 'checked');
                            $.post('${rootUri}/user-management/userState/' + $(e.target).attr('id') + '/' + isChecked);
                        });
                    }
            );
        </script>

    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/reset-password-ok.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="send.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/common-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="send.description"/></h3>

        <div class="sub-content">
            <p style="margin: 20px 0;">
                <fmt:message key="send.info">
                    <fmt:param value="${actionBean.resetEmail}"/>
                </fmt:message>
            </p>
            <a href="${rootUri}/login" class="btn btn-primary"><fmt:message key="send.login.label"/></a>
        </div>
    </s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/views/pages/setting.jsp
<%@include file="/WEB-INF/views/public/tagLib.jsp"%>
<fmt:message key="setting.log.type.title" var="titleStr"/>
<s:layout-render name="/WEB-INF/views/layout/login-layout.jsp" title="${titleStr}">
    <s:layout-component name="mainContent">
        <div class="page-header">
            <h2>${titleStr}</h2>
        </div>
        <h3 class="sub-content"><fmt:message key="setting.log.type.description"/></h3>
        <div class="form-box">
            <s:form beanclass="com.wiseach.teamlog.web.actions.SettingActionBean" class="form-inline">
                <div class="input-prepend">
                    <fmt:message key="setting.log.type.info" var="inputWorkType"/>
                    <span class="add-on"><i class="icon-th-large"></i></span><input id="workType" style="width: 740px;" name="workType" value="${actionBean.workType}" type="text" placeholder="${inputWorkType}" title="${inputWorkType}">
                </div>
                <s:submit name="create" class="btn btn-primary"><fmt:message key="button.ok.label"/></s:submit>
            </s:form>
            <s:errors field="workType"/>
        </div>

        <div class="form-box" style="padding-top: 0px;">
            <div class="clearfix" style="border: 1px solid #EEE;padding: 10px;">
                <c:if test="${actionBean.allWorkType!=null}">
                    <c:forEach items="${actionBean.allWorkType}" var="workType">
                        <div class="work-type">
                            ${workType.name}
                            <a class="btn btn-mini btn-danger del-work-type" title='<fmt:message key="setting.log.type.delete"/>' id="${workType.id}"><i class="icon-trash icon-white"></i></a>
                        </div>
                    </c:forEach>
                </c:if>
                <c:if test="${actionBean.allWorkType==null}">
                    <div class="warning"><fmt:message key="setting.log.type.warning.description" /></div>
                </c:if>
            </div>
            <a href="${rootUri}/invite-users/finish" class="btn btn-primary clearfix" style="margin-top: 20px;"><fmt:message key="setting.log.type.button.finish"/></a>
        </div>

        <script type="text/javascript">
            $(function () {
                        $('#inviteEmail').focus();
                        $('.del-work-type').hide().on('click',function(e) {
                            if (confirm('<fmt:message key="setting.log.type.delete.confirm"/>')) {
                                var $this = $(this);
                                $.post('${rootUri}/setting/deleteWorkType/',{typeId:$(this).attr('id')},function(d){
                                    if (d) {
                                        $this.parent().detach();
                                    }
                                });
                            }

                            e.preventDefault();
                        });
                        $('.work-type').hover(function(e){
                            $(this).css('background-color','#eff').find('a').show();
                        },function(){
                            $(this).css('background-color','transparent').find('a').hide();
                        });
                    }
            );
        </script>

    </s:layout-component>
</s:layout-render>